name: Check Updates

env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  FORKED_REPO: "https://github.com/TeamNewPipe/NewPipe"
  BRANCH: "dev"
  MY_REPO: "https://github.com/anhlahieupro/NewPipe"
  MY_NAME: "Hieu Dinh"

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Check Updates
      run: |
        MY_LAST_ID=""
        for number in 1 2 3 4 5; do
            if ! git log -n $number --format="%h %an" | tail -n 1 | grep -q $MY_NAME; then
                MY_LAST_ID=$(git log -n $number --format="%h" | tail -n 1)
                break
            fi
        done

        git remote add upstream $FORKED_REPO
        git fetch upstream >/dev/null 2>&1
        FORKED_LAST_ID=$(git log -n 1 --format="%h" "upstream/$BRANCH" | tail -n 1)

        echo $MY_LAST_ID
        echo $FORKED_LAST_ID

        if [ "$FORKED_LAST_ID" != "$MY_LAST_ID" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MY_REPO\"}" $WEBHOOK_URL
        fi
